const exampleData = [{ 
  name: 'Hall Eighteen Seventy-Three Cabernet Sauvignon 2013',
  url: 'http://www.wine.com/v6/Hall-Eighteen-Seventy-Three-Cabernet-Sauvignon-2013/wine/167260/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/167260m.jpg',
  type: 'Cabernet Sauvignon',
  region: 'Napa Valley',
  rating: 98,
  price: 79.99 
},
{ name: 'Antinori Tignanello 2013',
  url: 'http://www.wine.com/v6/Antinori-Tignanello-2013/wine/158020/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/158020m.jpg',
  type: 'Sangiovese',
  region: 'Tuscany',
  rating: 97,
  price: 89.99 
},
{ name: 'Silver Oak Alexander Valley Cabernet Sauvignon 2012',
  url: 'http://www.wine.com/v6/Silver-Oak-Alexander-Valley-Cabernet-Sauvignon-2012/wine/160512/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/160512m.jpg',
  type: 'Cabernet Sauvignon',
  region: 'Sonoma County',
  rating: 90,
  price: 69.99 
},
{ name: 'Hahn Winery Santa Lucia Highlands Pinot Noir 2014',
  url: 'http://www.wine.com/v6/Hahn-Winery-Santa-Lucia-Highlands-Pinot-Noir-2014/wine/153921/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/153921m.jpg',
  type: 'Pinot Noir',
  region: 'Central Coast',
  rating: 92,
  price: 22.99 
},
{ name: 'Antinori Tignanello 2013',
  url: 'http://www.wine.com/v6/Antinori-Tignanello-2013/wine/158020/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/158020m.jpg',
  type: 'Sangiovese',
  region: 'Tuscany',
  rating: 97,
  price: 89.99 
},
{ name: 'Antinori Tignanello 2013',
  url: 'http://www.wine.com/v6/Antinori-Tignanello-2013/wine/158020/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/158020m.jpg',
  type: 'Sangiovese',
  region: 'Tuscany',
  rating: 97,
  price: 89.99 
},
{ name: 'Silver Oak Alexander Valley Cabernet Sauvignon 2012',
  url: 'http://www.wine.com/v6/Silver-Oak-Alexander-Valley-Cabernet-Sauvignon-2012/wine/160512/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/160512m.jpg',
  type: 'Cabernet Sauvignon',
  region: 'Sonoma County',
  rating: 90,
  price: 69.99 
},
{ name: 'Quintessential Reds Wine Collection',
  url: 'http://www.wine.com/v6/Quintessential-Reds-Wine-Collection/gift/100296/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/100296m.jpg',
  type: 'Not available',
  region: 'Not available',
  rating: 0,
  price: 99.99 
},
{ name: 'Villeneuve Chateauneuf-du-Pape Vieilles Vignes 2012',
  url: 'http://www.wine.com/v6/Villeneuve-Chateauneuf-du-Pape-Vieilles-Vignes-2012/wine/166863/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/166863m.jpg',
  type: 'Rhone Red Blends',
  region: 'Chateauneuf-du-Pape',
  rating: 95,
  price: 49.99 
},
{ name: 'Quintessential Reds Wine Collection',
  url: 'http://www.wine.com/v6/Quintessential-Reds-Wine-Collection/gift/100296/Detail.aspx',
  labelUrl: 'http://cache.wine.com/labels/100296m.jpg',
  type: 'Not available',
  region: 'Not available',
  rating: 0,
  price: 99.99 
}];

module.exports.exampleData = exampleData;